a

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -46,7 +46,10 @@ jobs:
 
       - run: echo ${{ steps.setup-r.outputs.installed-r-version }}
 
-      - run: print("hello")
+      - run: |
+          Sys.setenv(RETICULATE_MINICONDA_PATH=Sys.getenv("CONDA"))
+          install.packages("reticulate")
+          reticulate::py_config()
         shell: Rscript {0}
 
 
@@ -56,10 +59,10 @@ jobs:
           echo "::set-output name=year-week::$(/bin/date -u "+%Y-%U")"
         shell: bash
 
-      - if: ${{ runner.os == 'macOS' }}
-        run: brew install tree
+      # - if: ${{ runner.os == 'macOS' }}
+      #   run: brew install tree
 
-      - run: tree $CONDA
+      # - run: tree $CONDA
 
       # - if: ${{ runner.os == 'Windows' }}
       #   run: choco install tree
@@ -87,5 +90,5 @@ jobs:
           conda info || echo "executable not found"
 
           ls -al $CONDA
-          tree $CONDA
-          $CONDA/bin/conda info || echo "executable not found"
+          # tree $CONDA
+          # $CONDA/bin/conda info || echo "executable not found"
